"""initial

Revision ID: e54ece0090cd
Revises: 
Create Date: 2026-04-10 17:49:08.779891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54ece0090cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('diary_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_pages_id'), 'diary_pages', ['id'], unique=False)
    op.create_index(op.f('ix_diary_pages_user_id'), 'diary_pages', ['user_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'normalized_name', name='uq_entity_user_type_name')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_normalized_name'), 'entities', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_entities_user_id'), 'entities', ['user_id'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_id'), 'entries', ['id'], unique=False)
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    op.create_table('entity_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('diary_page_id', sa.Integer(), nullable=False),
    sa.Column('mention_text', sa.String(length=255), nullable=False),
    sa.Column('sentence_text', sa.Text(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=32), nullable=True),
    sa.Column('emotion_label', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['diary_page_id'], ['diary_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_mentions_diary_page_id'), 'entity_mentions', ['diary_page_id'], unique=False)
    op.create_index(op.f('ix_entity_mentions_entity_id'), 'entity_mentions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_mentions_id'), 'entity_mentions', ['id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diary_page_id', sa.Integer(), nullable=False),
    sa.Column('subject_entity_id', sa.Integer(), nullable=True),
    sa.Column('predicate', sa.String(length=100), nullable=False),
    sa.Column('object_entity_id', sa.Integer(), nullable=True),
    sa.Column('object_text', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('time_text', sa.String(length=255), nullable=True),
    sa.Column('emotion_label', sa.String(length=32), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['diary_page_id'], ['diary_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_diary_page_id'), 'facts', ['diary_page_id'], unique=False)
    op.create_index(op.f('ix_facts_emotion_label'), 'facts', ['emotion_label'], unique=False)
    op.create_index(op.f('ix_facts_id'), 'facts', ['id'], unique=False)
    op.create_index(op.f('ix_facts_object_entity_id'), 'facts', ['object_entity_id'], unique=False)
    op.create_index(op.f('ix_facts_predicate'), 'facts', ['predicate'], unique=False)
    op.create_index(op.f('ix_facts_subject_entity_id'), 'facts', ['subject_entity_id'], unique=False)
    op.create_index(op.f('ix_facts_user_id'), 'facts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facts_user_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_subject_entity_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_predicate'), table_name='facts')
    op.drop_index(op.f('ix_facts_object_entity_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_emotion_label'), table_name='facts')
    op.drop_index(op.f('ix_facts_diary_page_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_entity_mentions_id'), table_name='entity_mentions')
    op.drop_index(op.f('ix_entity_mentions_entity_id'), table_name='entity_mentions')
    op.drop_index(op.f('ix_entity_mentions_diary_page_id'), table_name='entity_mentions')
    op.drop_table('entity_mentions')
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_id'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_entities_user_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_normalized_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_diary_pages_user_id'), table_name='diary_pages')
    op.drop_index(op.f('ix_diary_pages_id'), table_name='diary_pages')
    op.drop_table('diary_pages')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
